# Generated by Django 5.0 on 2023-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='documento',
            name='pdf',
            field=models.FileField(default=None, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissao',
            name='permissao',
            field=models.CharField(choices=[('R', 'Leitura'), ('W', 'Escrita'), ('C', 'Verificação')], max_length=1),
        ),
    ]
