# Generated by Django 5.0 on 2023-12-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documento_conteudo_documento_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissao',
            name='documento',
        ),
    ]
