# Generated by Django 5.0 on 2023-12-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_remove_permissao_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='criado_em',
        ),
    ]
